### PR TITLE
Added statsPlane to scene.

### PR DESCRIPTION
**Pull request by kikoano**
Added statsPlane to scene so it can render the stats when scene is rendered. Before scene was doing nothing and statsPlane was in no scene to be rendered.

### CODE REVIEW

**Review by Sean-Bradley — COMMENTED** [review]
This won't be merged.
Your fix actually breaks StatsVR, 
when you initialise StatsVR, you pass in an existing scene and camera,
```javascript
statsVR = new StatsVR(scene, camera);
```

The StatsVR panel is attached to the camera, so that it is always in front of you when you move your VR headset around.
Your fix, makes the StatsVR panel positioned statically in the scene, which is more like the original stats.js library written by Mr Doob, that inspired my project. [http://mrdoob.github.io/stats.js/](http://mrdoob.github.io/stats.js/
)
Maybe that would be better use for you.

Look at my StatsVR demos, read the instructions and watch the videos, and you will see that it works. 
The panel, is relative to the view of your headset, so that you can always see the stats, even if you turn your head.
I think you are trying to achieve something StatsVR wasn't written to do.

**Comment by kikoano** [comment]
For me it never worked without being added in the scene. Maybe because when
VR enabled in Three. js it creates new special camera.

**Comment by Sean-Bradley** [comment]
Maybe you could put your script on GitHub, and I can look at it to see what might be wrong.
Otherwise, I have even more demos that use StatsVR successfully.
[https://sean-bradley.github.io/GrabVR/](https://sean-bradley.github.io/GrabVR/)
[https://sean-bradley.github.io/TeleportVR/](https://sean-bradley.github.io/TeleportVR/)

**Comment by kikoano** [comment]
> Maybe you could put your script on GitHub, and I can look at it to see what might be wrong.
> Otherwise, I have even more demos that use StatsVR successfully.
> https://sean-bradley.github.io/GrabVR/
> https://sean-bradley.github.io/TeleportVR/

Found my problem i forgot to add my camera to my scene. Now it works.

**Pull request closed without merging**
